name: Authenticator UI CI
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract version from package.json
        id: extract_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image with version tag
        run: docker build -t suleimanmoraes/authenticator-ui:${{ env.VERSION }} .

      - name: Tag Docker image as latest
        run: docker tag suleimanmoraes/authenticator-ui:${{ env.VERSION }} suleimanmoraes/authenticator-ui:latest

      - name: Push Docker image with version tag
        run: docker push suleimanmoraes/authenticator-ui:${{ env.VERSION }}

      - name: Push Docker image with latest tag
        run: docker push suleimanmoraes/authenticator-ui:latest

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.PATH_DOCKER_COMPOSE }}
            docker-compose pull
            docker-compose up -d
            docker image prune -f
